### ISSUE TITLE
Errors when migrating on schema version 130

### ISSUE THREAD

**Issue by rmarchant** [hrk/tt-rss-mysql2pgsql#2]
psql (PostgreSQL) 9.4.5
mysqld 5.5.47

Receiving the following errors with both mysql and psql databases on schema version 130:

`ERROR: Batch entry 0 INSERT INTO ttrss_users(id, login, pwd_hash, last_login, access_level, theme_id, email, full_name, email_digest, last_digest_sent, salt, created, twitter_oauth, otp_enabled, resetpass_token) VALUES (1, 'admin', 'MODE2:#########################################################', '2013-03-31 22:49:49.000000 +02:00:00', 10, NULL, '', '', '0', NULL, 'b27b8d892ed611266cd6c989907528cc565841f884200a94df44ee6dbcbf5d03a859f2ac4dcfb128f5fd073c559107fcfc3bb8bed2a21c31e475fd0a0b52200c9ec850f6dee01f70e87f84edf493467e5ca90185076ca395ef837c0a9c771b69dc199f3f544e4f3d9bc6ddc88c993d5b36c359fd50ad312c9a9fc287ca', NULL, NULL, '0', NULL) was aborted.  Call getNextException to see the cause.
CAUSE: ERROR: column "theme_id" of relation "ttrss_users" does not exist`

`'CAUSE: ERROR: insert or update on table "ttrss_user_entries" violates foreign key constraint "ttrss_user_entries_feed_id_fkey"
  Detail: Key (feed_id)=(3) is not present in table "ttrss_feeds".
ERROR: Batch entry 0 INSERT INTO ttrss_user_entries(int_id, ref_id, uuid, feed_id, orig_feed_id, owner_uid, marked, published, tag_cache, label_cache, last_read, score, note, unread, last_marked, last_published) VALUES (1254, 1203, '', 12, NULL, 1, '0', '0', '', '{"no-labels":1}', NULL, 0, NULL, '1', NULL, NULL) was aborted.  Call getNextException to see the cause.
CAUSE: ERROR: insert or update on table "ttrss_user_entries" violates foreign key constraint "ttrss_user_entries_feed_id_fkey"
  Detail: Key (feed_id)=(12) is not present in table "ttrss_feeds".
ERROR: Batch entry 0 INSERT INTO ttrss_user_entries(int_id, ref_id, uuid, feed_id, orig_feed_id, owner_uid, marked, published, tag_cache, label_cache, last_read, score, note, unread, last_marked, last_published) VALUES (1868, 1817, '', 21, NULL, 1, '0', '0', '', '{"no-labels":1}', NULL, 0, NULL, '1', NULL, NULL) was aborted.  Call getNextException to see the cause.
CAUSE: ERROR: insert or update on table "ttrss_user_entries" violates foreign key constraint "ttrss_user_entries_feed_id_fkey"
  Detail: Key (feed_id)=(21) is not present in table "ttrss_feeds".'`

**Comment by hrk** [comment]
The first error reports.

```
ERROR: column "theme_id" of relation "ttrss_users" does not exist
```

This makes me think that if you are sure that both schemas are at the same version (130), then check if some of the schema updates went wrong, since it's clearly missing a column. I'd recommend completely deleting the PGSQL database and create it from scratch.

**Comment by rmarchant** [comment]
Thanks for pointing that out. Apparently the theme_id column was removed a
few versions ago as it had no use. I still ran into issues after removing
the column and trying to migrate again:
- The schema inserts the default admin user
- Your script tries to replace this row, errors, then stops inserting data into the table (even though there were more entries to add)
- This causes inserts in other tables that are linked to the missing users
  to fail

**Comment by rmarchant** [comment]
And the fix was to simply delete the default admin account from the table prior to migrating. Thanks for your awesome tool!

**Comment by florian-asche** [comment]
Thanks! Your workaround works great.
And some help more for the people after me: you need enough memory!

**Comment by magne4000** [comment]
Should probably reopen this issue, it should be fixed
