### ISSUE TITLE
Issues with timestamp

### ISSUE THREAD

**Issue by Akegata** [hrk/tt-rss-mysql2pgsql#3]
I'm trying to migrate my tt-rss setup to pgsql but get the following error:
`$ java -jar tt-rss-mysql2pgsql.jar 
INSERT INTO ttrss_users(id, login, pwd_hash, last_login, access_level, theme_id, email, full_name, email_digest, last_digest_sent, salt, created, twitter_oauth, otp_enabled, resetpass_token) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ERROR: Batch entry 0 INSERT INTO ttrss_users(id, login, pwd_hash, last_login, access_level, theme_id, email, full_name, email_digest, last_digest_sent, salt, created, twitter_oauth, otp_enabled, resetpass_token) VALUES (1, 'admin', 'MODE2:60b37441290e7550e42f24ba8500aa8732b21771a357da7e620b9ffdd84b1461', '2013-03-30 20:56:26.000000 +01:00:00', 10, NULL, '', '', '0', NULL, 'e49ee91dd49ab5de4df22d3e38c7a0f23faee6a7b5b624a227bdf67e9f91266304d5d649e0f9d3e0cba8e95eb15b268f7d98923f0063fcee41eab702edd38ec3aebb76c10ae0551dc60e87073a29e469b9baa2a90a48785c651105b0eb9f60221e219571f66a16d64a7baf0771a6efceb590cabb0a56a04e6589e840ab', NULL, NULL, '0', NULL) was aborted.  Call getNextException to see the cause.
CAUSE: ERROR: column "theme_id" of relation "ttrss_users" does not exist
  Position: 72
[ttrss_users] 9 ms.
[ttrss_users] setting sequence to 3
INSERT INTO ttrss_feed_categories(id, owner_uid, title, collapsed, order_id, parent_cat, view_settings) VALUES (?, ?, ?, ?, ?, ?, ?)
ERROR: Batch entry 0 INSERT INTO ttrss_feed_categories(id, owner_uid, title, collapsed, order_id, parent_cat, view_settings) VALUES (1, 2, 'flickr', '0', 7, NULL, '') was aborted.  Call getNextException to see the cause.
CAUSE: ERROR: insert or update on table "ttrss_feed_categories" violates foreign key constraint "ttrss_feed_categories_owner_uid_fkey"
  Detail: Key (owner_uid)=(2) is not present in table "ttrss_users".
[ttrss_feed_categories] 3 ms.
[ttrss_feed_categories] setting sequence to 7
INSERT INTO ttrss_feeds(id, owner_uid, title, cat_id, feed_url, icon_url, update_interval, purge_interval, last_updated, last_error, site_url, auth_login, auth_pass, parent_feed, private, rtl_content, hidden, include_in_digest, cache_images, hide_images, cache_content, auth_pass_encrypted, last_viewed, last_update_started, always_display_enclosures, update_method, order_id, mark_unread_on_update, update_on_checksum_change, strip_images, pubsub_state, favicon_last_checked, view_settings, favicon_avg_color, feed_language) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Exception in thread "main" java.sql.SQLException: Value '563iny Tiny RSS: New Releases�http://tt-rss.org/releases.rss000000-00-00 00:00:00�00010000�2013-04-29 20:30:010000000��' can not be represented as java.sql.Timestamp
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)
	at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:935)
	at com.mysql.jdbc.BufferRow.getTimestampFast(BufferRow.java:555)
	at com.mysql.jdbc.ResultSetImpl.getTimestampInternal(ResultSetImpl.java:5956)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:5624)
	at it.sineo.ttrssMySQL2PGSQL.Sync.main(Sync.java:148)
`

**Comment by hrk** [comment]
Sorry for the delay. I'm not even sure you still require assistance or feedback, but the issue is not with the timestamp. The first reported error is this one:

CAUSE: ERROR: column "theme_id" of relation "ttrss_users" does not exist

which means your mysql and pgsql schemas differ. This may be due to:
1. Your MySQL database has a different schema version than the PGSQL one. This is bad. First run every schema version update, then launch the tool.
2. During the life of your MySQL install, some schema version update failed. More specific: the "83" schema version dropped the theme_id column.

So either you're trying to migrate a 83-schema to a newer schema, or the 83-update went bad.
